name: Terraform Deploy to AWS

on:
  workflow_dispatch:

jobs:
  build:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    
    environment:
      name: staging

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.8

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Get Session Token
      run: echo aws sts get-session-token        

    - name: Initialize Terraform VPC
      working-directory: ./src/1-vpc
      run: terraform init

    - name: Terraform Plan VPC
      working-directory: ./src/1-vpc
      run: terraform plan -out=tfplan

    - name: Terraform Apply VPC
      working-directory: ./src/1-vpc
      run: terraform apply -auto-approve tfplan

    - name: Initialize Terraform SQS
      working-directory: ./src/2-sqs
      run: terraform init

    - name: Terraform Plan SQS
      working-directory: ./src/2-sqs
      run: terraform plan -out=tfplan

    - name: Terraform Apply SQS
      working-directory: ./src/2-sqs
      run: terraform apply -auto-approve tfplan

    - name: Initialize Terraform DynamoDB
      working-directory: ./src/3-dynamodb
      run: terraform init

    - name: Terraform Plan DynamoDB
      working-directory: ./src/3-dynamodb
      run: terraform plan -out=tfplan

    - name: Terraform Apply DynamoDB
      working-directory: ./src/3-dynamodb
      run: terraform apply -auto-approve tfplan      

    - name: Initialize Terraform EKS
      working-directory: ./src/4-eks
      run: terraform init

    - name: Terraform Plan EKS
      working-directory: ./src/4-eks
      run: terraform plan -out=tfplan

    - name: Terraform Apply EKS
      working-directory: ./src/4-eks
      run: terraform apply -auto-approve tfplan       
           